name: Compile and deploy

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

  push:
    branches: [master]

jobs:
  build:
    name: Compile and deploy
    environment:
      name: ATE47 Profile
      url: "https://github.com/ate47"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: ./download_old.sh
      - run: node index.js
        env:
          APIKEY_CURSEFORGE: ${{ secrets.APIKEY_CURSEFORGE }}
          APIKEY_MODRINTH: ${{ secrets.APIKEY_MODRINTH }}
      - name: Deploy md to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          repo: ate47/ate47
          build_dir: out
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
